version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "JoaoSantosCodes"
    assignees:
      - "JoaoSantosCodes"
    commit-message:
      prefix: "deps"
      include: "scope"
